locale: ~
navigation:
  uppercase: true
text:
  showDate: false
footer:
  copyright: "&copy; 2018. <a href=\"mailto:paikwiki@gmail.com\">paikwiki</a>.<br/>This website is made with <a href=\"https://github.com/jekyll-theme-lightning/lightning\">Lighting theme</a>.<br/> Feel free to use it under the <a href=\"https://www.olis.or.kr/license/Detailselect.do?lId=1006&mapCode=010006\">MIT license</a>."